'use strict'


module.exports = {
    PROCESS_STATUS_CODE_INITIALIZED: 'INT',
    PROCESS_STATUS_CODE_IN_PROGRESS: 'PRG',
    PROCESS_STATUS_CODE_COMPLETED: 'CMP',
    PROCESS_STATUS_CODE_PENDING: 'PND',
    PROCESS_STATUS_CODE_FAILED: 'FLD',
}